---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_connection: community.docker.docker
      ansible_host: clickhouse-01
      ansible_user: root
      ansible_python_interpreter: /usr/bin/python3
vector:
  hosts:
    vector-01:
      ansible_connection: community.docker.docker
      ansible_host: vector-01
      ansible_user: root
      ansible_python_interpreter: /usr/bin/python3
lighthouse:
  hosts:
    lighthouse-01:
      ansible_connection: community.docker.docker
      ansible_host: lighthouse-01
      ansible_user: root
      ansible_python_interpreter: /usr/bin/python3
